-- Drop and recreate Todos table

DROP TABLE IF EXISTS todos CASCADE;
CREATE TABLE todos (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT NOW(),
  done BOOLEAN NOT NULL DEFAULT FALSE
);
